#### 라이브러리 임포트

In [13]:
import pandas as pd
import os
import glob
from openpyxl import load_workbook

path = os.chdir('/Users/bestw/Desktop/ex/python_ex/PythonProject/개인학습/git_local_folder/일잘러 파이썬과 40개의 작품들 책 소스 코드/2.여러개의 엑셀 발주수량 합치기')
order_files = [file for file in os.listdir(path)
               if file.endswith('.xlsx') and
               not file.startswith('통합') and
               not file.startswith('result')]

print(f"order_files: {order_files}")

order_position_list = []
order_product_list = []
order_quantity_list = []

for file in order_files:
    wb = load_workbook(file, data_only=True)
    ws = wb.active

    order_position = ws['B1'].value
    print(f'order_position : {order_position}')

    for order_product, order_quantity in ws.iter_rows(
        min_row=4,
        max_row=12,
        min_col=1,
        max_col=2,
        values_only=True
    ):
        if order_product is not None:
            order_position_list.append(order_position)
            order_product_list.append(order_product)
            order_quantity_list.append(order_quantity)

    wb.close()

print(f'order_position_list : {order_position_list}')
print(f'order_product_list : {order_product_list}')
print(f'order_quantity_list : {order_quantity_list}')

df = pd.DataFrame({
    'order_position': order_position_list,
    'order_product': order_product_list,
    'order_quantity': order_quantity_list
})

df.head()

order_files: ['발주서_해운대.xlsx', '발주서_시흥.xlsx', '발주서_청주.xlsx']
order_position : 해운대
order_position : 시흥
order_position : 청주
order_position_list : ['해운대', '해운대', '해운대', '시흥', '시흥', '청주', '청주', '청주']
order_product_list : ['연필', '볼펜', '필통', '연필', '자', 'A4용지', '볼펜', '연필']
order_quantity_list : [50, 100, 10, 100, 150, 100, 50, 50]

  order_position order_product  order_quantity
0            해운대            연필              50
1            해운대            볼펜             100
2            해운대            필통              10
3             시흥            연필             100
4             시흥             자             150

In [12]:
order_position_list = []
order_product_list = []
order_quantity_list = []

for file in order_files:
    wb = load_workbook(file, data_only=True)
    ws = wb.active

    order_position = ws['B1'].value
    print(f'order_position : {order_position}')

    for order_product, order_quantity in ws.iter_rows(
        min_row=4,
        max_row=12,
        min_col=1,
        max_col=2,
        values_only=True
    ):
        if order_product is not None:
            order_position_list.append(order_position)
            order_product_list.append(order_product)
            order_quantity_list.append(order_quantity)

    wb.close()

print(f'order_position_list : {order_position_list}')
print(f'order_product_list : {order_product_list}')
print(f'order_quantity_list : {order_quantity_list}')

df = pd.DataFrame({
    'order_position': order_position_list,
    'order_product': order_product_list,
    'order_quantity': order_quantity_list
})

df.head(10)

order_position : 해운대
order_position : 시흥
order_position : 청주
order_position_list : ['해운대', '해운대', '해운대', '시흥', '시흥', '청주', '청주', '청주']
order_product_list : ['연필', '볼펜', '필통', '연필', '자', 'A4용지', '볼펜', '연필']
order_quantity_list : [50, 100, 10, 100, 150, 100, 50, 50]

  order_position order_product  order_quantity
0            해운대            연필              50
1            해운대            볼펜             100
2            해운대            필통              10
3             시흥            연필             100
4             시흥             자             150
5             청주          A4용지             100
6             청주            볼펜              50
7             청주            연필              50