## 8.1 기본 파이썬 기능으로 테이블 저장하기

In [7]:
# code 8-1 파이썬 딕셔너리 자료 구조로 테이블 저장하기
fish_measures = {
    'Fish'   : ['Angelfish', 'Zebrafish', 'Killfish', 'Swordfish'],
    'Length' : [15.2, 6.5, 9, 6],
    'Width'  : [7.7, 2.1, 4.5, 2]
}

# code 8-2 딕서너리로 테이블 접급하기
zebrafish_index = fish_measures['Fish'].index('Zebrafish')
zebrafish_length = fish_measures['Length'][zebrafish_index]
print(f' {zebrafish_index} : zebrafish 길이는 {zebrafish_length:.2f} cm')

 1 : zebrafish 길이는 6.50 cm

## 8.2 판다스로 테이블 탐색하기

In [13]:
# code 8-3 판다스 라이브러리 블러오기
import pandas as pd
import numpy as np

# code 8-4 테이블을 판다스의 데이터 프레임 형식으로 변환하기
df = pd.DataFrame(fish_measures)
print(df)

        Fish  Length  Width
0  Angelfish    15.2    7.7
1  Zebrafish     6.5    2.1
2   Killfish     9.0    4.5
3  Swordfish     6.0    2.0

In [9]:
# code 8-5 테이블의 첫 두 행의 접급하기
print(df.head(2))

        Fish  Length  Width
0  Angelfish    15.2    7.7
1  Zebrafish     6.5    2.1

In [10]:
# code 8-6 숫자열 요약하기
df.describe()

          Length     Width
count   4.000000  4.000000
mean    9.175000  4.075000
std     4.225616  2.678775
min     6.000000  2.000000
25%     6.375000  2.075000
50%     7.750000  3.300000
75%    10.550000  5.300000
max    15.200000  7.700000

In [11]:
# code 8-7 열의 평균 계산하기
print(df.iloc[:,1:].mean())

Length    9.175
Width     4.075
dtype: float64

In [14]:
# code 8-8 문자열 요약하기
print(df.describe(include=[np.object_]))

             Fish
count           4
unique          4
top     Angelfish
freq            1

In [15]:
# code 8-9 테이블을 2차원 넘파이 배열로 가져오기
print(df.values)
assert type(df.values) == np.ndarray

[['Angelfish' 15.2 7.7]
 ['Zebrafish' 6.5 2.1]
 ['Killfish' 9.0 4.5]
 ['Swordfish' 6.0 2.0]]

## 8.3 테이블 열 가져오기

In [16]:
# code 8-10 모든 열 이름에 접근하기
print(df.columns)

Index(['Fish', 'Length', 'Width'], dtype='object')

In [17]:
# code 8-11 개별 열에 접근하기
print(df.Fish)

0    Angelfish
1    Zebrafish
2     Killfish
3    Swordfish
Name: Fish, dtype: object

## 8.5 테이블의 행과 열 수정하기

In [ ]:
df.set_index('Fish', inplace=True)

In [28]:
# code 8-22 행과 열 바꾸기
df_transposed =df.T
print(df_transposed)

Fish    Angelfish  Zebrafish  Killfish  Swordfish
Length       15.2        6.5       9.0        6.0
Width         7.7        2.1       4.5        2.0

In [30]:
# code 8-24 신규 열 추가하기
df_transposed['Clownfish'] = [10.6, 3.7]
print(df_transposed)

Fish    Angelfish  Zebrafish  Killfish  Swordfish  Clownfish
Length       15.2        6.5       9.0        6.0       10.6
Width         7.7        2.1       4.5        2.0        3.7

In [31]:
# code 8-25 신규 열을 여러 개 추가하기
df_new = df_transposed.assign(Clownfish2=[10.6,3.7], Clownfish3=[10.6,3.7])
assert 'Clownfish2' not in df_transposed.columns
assert 'Clownfish2' in df_new.columns
print(df_new)

Fish    Angelfish  Zebrafish  Killfish  Swordfish  Clownfish  Clownfish2  \
Length       15.2        6.5       9.0        6.0       10.6        10.6
Width         7.7        2.1       4.5        2.0        3.7         3.7

Fish    Clownfish3
Length        10.6
Width          3.7

In [32]:
# code 8-26 여러 열 삭제하기
df_new.drop(columns=['Clownfish2','Clownfish3'], inplace=True)
df_new

Fish    Angelfish  Zebrafish  Killfish  Swordfish  Clownfish
Length       15.2        6.5       9.0        6.0       10.6
Width         7.7        2.1       4.5        2.0        3.7

In [33]:
with open('Friendships.csv') as f:
    print(f.read())

Friend_A,Friend_B
b8bc075e54b9,49194b3720b6
b8bc075e54b9,f0f5962bbc52
b8bc075e54b9,d42f06d92a52
b8bc075e54b9,81123b29ee66
b8bc075e54b9,b1b65a546a3e
b8bc075e54b9,b712b1359e68
b8bc075e54b9,c2833a91454a
b8bc075e54b9,993a9b1dc2ef
b8bc075e54b9,1d54d57a01a7
b8bc075e54b9,79ff489ecbc1
b8bc075e54b9,9e5bec3ed583
b8bc075e54b9,ac5577bc1a57
b8bc075e54b9,bd51b54aa99c
b8bc075e54b9,4ebf721a9462
b8bc075e54b9,f654a40a9376
b8bc075e54b9,b4bbd056ae56
b8bc075e54b9,83c0e39eb091
b8bc075e54b9,2e79cae5ff8c
b8bc075e54b9,2e935226520b
b8bc075e54b9,c4f33679edb6
b8bc075e54b9,cbba789fcc68
b8bc075e54b9,f8b71643a4c1
b8bc075e54b9,44946ad84360
b8bc075e54b9,c256266e0958
b8bc075e54b9,ba4dd06ef108
b8bc075e54b9,307cbfe561e1
b8bc075e54b9,817d28fcd51f
b8bc075e54b9,8de38b5be85e
b8bc075e54b9,985e342b613a
b8bc075e54b9,2631addff82d
b8bc075e54b9,9a058cf2e094
b8bc075e54b9,61dcaf381ffe
b8bc075e54b9,ad7e37d49cb8
b8bc075e54b9,5c1ac5c4ae34
b8bc075e54b9,de2965ac31c3
b8bc075e54b9,cb0f5998e796
b8bc075e54b9,2007780558c9
b8bc075e54b9,07921bdec548
b8bc075e54b9,75f2e606f05c
b8bc075e54b9,45a669e4fc6a
b8bc075e54b9,1e498fd35e79
b8bc075e54b9,b58535395a0e
b8bc075e54b9,bb37036f9c97
b8bc075e54b9,08452885ff12
b8bc075e54b9,f45207fec6ba
b8bc075e54b9,6cd965e6987b
b8bc075e54b9,f7c8b901f6d3
b8bc075e54b9,057b9bfb4420
b8bc075e54b9,956a8e33023f
b8bc075e54b9,fc26407908c0
b8bc075e54b9,eb0037580902
b8bc075e54b9,f7b62a0558fa
b8bc075e54b9,d627522f3984
b8bc075e54b9,c391658a19c7
b8bc075e54b9,333de2dc16dc
b8bc075e54b9,1e6e14ca2e81
b8bc075e54b9,740522c85adc
b8bc075e54b9,b5e368c3f830
b8bc075e54b9,d2813865c79c
b8bc075e54b9,88be06d25a00
b8bc075e54b9,440af1812334
b8bc075e54b9,31cb4a596cdc
b8bc075e54b9,e08f32a63a29
b8bc075e54b9,72255340fb39
b8bc075e54b9,498fb98f60ad
b8bc075e54b9,05e4c05872de
b8bc075e54b9,68a329c47450
b8bc075e54b9,685afaed9867
b8bc075e54b9,69783db11b2c
b8bc075e54b9,6f2dca6345d0
b8bc075e54b9,2a6fffc3967d
b8bc075e54b9,75cb518fc43a
b8bc075e54b9,dc42eb35fdc2
b8bc075e54b9,e84bfb0974bb
b8bc075e54b9,83c1cc7798a8
b8bc075e54b9,5613f7f5b5cc
b8bc075e54b9,aba97ea00ac8
b8bc075e54b9,2e1f49d39407
b8bc075e54b9,40f7e1e55de6
b8bc075e54b9,52102636a852
b8bc075e54b9,cfd33488c7a8
b8bc075e54b9,ff7499af5148
b8bc075e54b9,0776cf5a0850
b8bc075e54b9,3c39f7406253
b8bc075e54b9,fad9e7cdced2
b8bc075e54b9,a17b54d02266
b8bc075e54b9,2fa428847959
b8bc075e54b9,17cdaa697248
b8bc075e54b9,15c0812dceff
b8bc075e54b9,7d2f5e4f4b42
b8bc075e54b9,0067b245d95d
b8bc075e54b9,73bb8bfd3e3d
b8bc075e54b9,5934010f41da
b8bc075e54b9,7e49bcf5ebb3
b8bc075e54b9,d19a3fd66a47
b8bc075e54b9,ade9985c7d67
b8bc075e54b9,34f888f96e03
b8bc075e54b9,b3a4c8f2a36b
b8bc075e54b9,d3d5d226a79b
b8bc075e54b9,2013a3bf052c
b8bc075e54b9,f5e2392562b2
b8bc075e54b9,3d12202399dc
b8bc075e54b9,51d1ba826cae
b8bc075e54b9,742b6e5b64d7
b8bc075e54b9,83b10ce23373
b8bc075e54b9,b850b3434462
b8bc075e54b9,89581f99fa1e
b8bc075e54b9,cd4efa39228a
b8bc075e54b9,55818c401f3a
b8bc075e54b9,6dbf201074fb
b8bc075e54b9,8700ea0ec29d
b8bc075e54b9,3617f6cbcded
b8bc075e54b9,55fcf51c7aa0
b8bc075e54b9,cdcb129fb070
b8bc075e54b9,6f74ac703ce5
b8bc075e54b9,dfc5f5d28951
b8bc075e54b9,af53789b6fd0
b8bc075e54b9,c37579407447
b8bc075e54b9,47d9a9418d7a
b8bc075e54b9,bc6c704292ad
b8bc075e54b9,68d8e44b5776
b8bc075e54b9,28e6c0f5e52e
b8bc075e54b9,80b059535dc9
b8bc075e54b9,af1ea5d543a6
b8bc075e54b9,b905b3f59b30
b8bc075e54b9,a34eff021e02
b8bc075e54b9,676e3d882946
b8bc075e54b9,fe38f482a16e
b8bc075e54b9,93ded5f4a9a2
b8bc075e54b9,c8823edd6529
b8bc075e54b9,f2da141a5410
b8bc075e54b9,ae4e99731f02
b8bc075e54b9,cc2a82038185
b8bc075e54b9,f7725a623ac8
b8bc075e54b9,97339f2c20f9
b8bc075e54b9,d675d6e7b7a6
b8bc075e54b9,b2e9130ceb77
b8bc075e54b9,63ab94d24452
b8bc075e54b9,9b0506775fd6
b8bc075e54b9,b27c1f55f390
b8bc075e54b9,0fcd9bb9fc31
b8bc075e54b9,f2ea8d8104df
b8bc075e54b9,907004f1060e
b8bc075e54b9,a8e84e79fd16
b8bc075e54b9,ad92bdd6f58f
b8bc075e54b9,94db0810f74f
b8bc075e54b9,511654bb6c8d
b8bc075e54b9,9b7a5086a83b
b8bc075e54b9,3a78f54b92b8
b8bc075e54b9,dd6db17ebab2
b8bc075e54b9,b2794e41d0cc
b8bc075e54b9,846e2499e288
b8bc075e54b9,b10e2efe5e96
b8bc075e54b9,8667c0c24db4
b8bc075e54b9,0491a87eca39
b8bc075e54b9,a409c26e11ec
b8bc075e54b9,f398e1781b61
b8bc075e54b9,67971a1581b4
b8bc075e54b9,bcf9895c77e8
b8bc075e54b9,1863ea8d8306
b8bc075e54b9,76d3592668ee
b8bc075e54b9,375338afd04b
b8bc075e54b9,cb3c9de37b7e
b8bc075e54b9,e81599b5162b
b8bc075e54b9,6a5e3c080139
b8bc075e54b9,708b0eeef12d
b8bc075e54b9,1869c788c56c
b8bc075e54b9,caa08f80c71b
b8bc075e54b9,047174fbec38
b8bc075e54b9,b04034ef703e
b8bc075e54b9,dfd572ac8b64
b8bc075e54b9,c920d8c7a90a
b8bc075e54b9,ea4b8b014ddd
b8bc075e54b9,be930e7580f2
b8bc075e54b9,d14046199f56
b8bc075e54b9,2715a83c4a9d
b8bc075e54b9,7ff927678ee2
b8bc075e54b9,24b4f4d707f9
b8bc075e54b9,b96832a5e862
b8bc075e54b9,5efe3e485d24
b8bc075e54b9,6bcf6e2c5e65
b8bc075e54b9,86dc92a0b236
b8bc075e54b9,7c97b124fc9e
b8bc075e54b9,affc5cad4bbf
b8bc075e54b9,343f5345b6b9
b8bc075e54b9,2170d3b4ad9e
b8bc075e54b9,b2612726fe0a
b8bc075e54b9,4539897211ee
b8bc075e54b9,f94e55ed6739
b8bc075e54b9,3afb02ef6420
b8bc075e54b9,2c8b74c79cec
b8bc075e54b9,f1e25328ff7c
b8bc075e54b9,7781f0de6ec5
b8bc075e54b9,7819c621e29e
b8bc075e54b9,fa7b3e50f363
b8bc075e54b9,5eae191f1a3d
b8bc075e54b9,2e45ab95414f
b8bc075e54b9,d86522ac043a
b8bc075e54b9,74d3e94c38d3
b8bc075e54b9,21f8c9514f94
b8bc075e54b9,891b42ed781b
b8bc075e54b9,b791d7a01e8e
b8bc075e54b9,794bc256e2a8
b8bc075e54b9,d4d1284b0171
b8bc075e54b9,fed4ea0307e2
b8bc075e54b9,f4efdfb9a5ef
b8bc075e54b9,234703afb24d
b8bc075e54b9,5b2b9b302eac
b8bc075e54b9,3ae230548420
b8bc075e54b9,05a4659fe648
b8bc075e54b9,ef005800712a
b8bc075e54b9,ada5696ad597
b8bc075e54b9,496f9568e2f3
b8bc075e54b9,66424a2f0ee2
b8bc075e54b9,e6099748f49b
b8bc075e54b9,06f1d0b5dd5e
b8bc075e54b9,b4adb4694398
b8bc075e54b9,82d7669e7ef3
b8bc075e54b9,046be2240556
b8bc075e54b9,c8b91184e67d
b8bc075e54b9,f44ff56c2769
b8bc075e54b9,627abf725049
b8bc075e54b9,c45efbd21270
b8bc075e54b9,5cf03340ca7a
b8bc075e54b9,b8671741d2e3
b8bc075e54b9,86ea8846e3b8
b8bc075e54b9,e9beb574a089
b8bc075e54b9,c595540965cd
b8bc075e54b9,eb81ccb9bdb7
b8bc075e54b9,c94af46d6fe7
b8bc075e54b9,c674da4a8e15
b8bc075e54b9,c25036408eef
b8bc075e54b9,66fc539eb263
b8bc075e54b9,7c1401f02e94
b8bc075e54b9,00c9cb6a1baa
b8bc075e54b9,14a76ad97098
b8bc075e54b9,954f9dc02c38
b8bc075e54b9,b48207900b75
b8bc075e54b9,6fc4693e7953
b8bc075e54b9,2040929b91d8
b8bc075e54b9,e0d3d1058e88
b8bc075e54b9,715f6cc1b260
b8bc075e54b9,b495840d09fe
b8bc075e54b9,f5c0e622d47c
b8bc075e54b9,29433f28f16a
b8bc075e54b9,a8874b9e61b9
b8bc075e54b9,20cdabcf47a1
b8bc075e54b9,ac6f84e69823
b8bc075e54b9,cae91f31aa84
b8bc075e54b9,3f1e946d85e8
b8bc075e54b9,3d79e076cf01
b8bc075e54b9,a6251a50e6c5
b8bc075e54b9,f464f8ec9c3b
b8bc075e54b9,5d4d22f4240a
b8bc075e54b9,de042a8457dc
b8bc075e54b9,0a0f902dc7c6
b8bc075e54b9,132aa73e02b2
b8bc075e54b9,e3a14c0757e2
b8bc075e54b9,38c13d1ef64f
b8bc075e54b9,5325582497f6
b8bc075e54b9,b44b67bfcbd8
b8bc075e54b9,764acbe22533
b8bc075e54b9,3c4c9b30c08c
b8bc075e54b9,08c8ca492c96
b8bc075e54b9,8f72f6bc69e5
b8bc075e54b9,e5160cec7608
b8bc075e54b9,0289cf827470
b8bc075e54b9,357b475d6e64
b8bc075e54b9,0fd390170ae9
b8bc075e54b9,c35cb09ad753
b8bc075e54b9,88f358a6080a
b8bc075e54b9,5446c664fe14
b8bc075e54b9,df45b11bd8d5
b8bc075e54b9,93ec94496e8e
b8bc075e54b9,b0b3a30d69e7
b8bc075e54b9,995122436f7b
b8bc075e54b9,20f5c0dc2f23
b8bc075e54b9,398e98f02bd1
b8bc075e54b9,249193a89dc6
b8bc075e54b9,60c9400712b3
b8bc075e54b9,233a7ee80e3b
b8bc075e54b9,7c944284ddb1
b8bc075e54b9,ea0ab6875037
b8bc075e54b9,bc91db5c349c
b8bc075e54b9,a2c31422625c
b8bc075e54b9,4110feaa2166
b8bc075e54b9,e6c3cbf4d69a
b8bc075e54b9,41d0f5691fa4
b8bc075e54b9,a5d1dfaf0bba
b8bc075e54b9,d37b23aa26a9
b8bc075e54b9,ed4c1ddc5aae
b8bc075e54b9,3d35793aeee3
b8bc075e54b9,58a9e2f8cdc3
b8bc075e54b9,3827557c477a
b8bc075e54b9,2c4cac92459a
b8bc075e54b9,097ad833f718
b8bc075e54b9,924f73dea209
b8bc075e54b9,8ac68679c8c7
b8bc075e54b9,0e90502cef04
b8bc075e54b9,c072286f85f3
b8bc075e54b9,210bfdf30313
b8bc075e54b9,f78244826bcd
b8bc075e54b9,3d7f812b7899
b8bc075e54b9,d93100708b01
b8bc075e54b9,175706d89285
b8bc075e54b9,24d0660aca2f
b8bc075e54b9,c39c48a587e4
b8bc075e54b9,1489f5578712
b8bc075e54b9,6bd48b38537a
b8bc075e54b9,51f45ed19f95
b8bc075e54b9,c4ea1035a0b6
b8bc075e54b9,1c9a5e4f9641
b8bc075e54b9,45ee2528da2b
b8bc075e54b9,ee78168c6a5b
b8bc075e54b9,65abc03ca0d4
b8bc075e54b9,823c1b7a7c53
b8bc075e54b9,aefc06ff8506
b8bc075e54b9,5beedf1a1158
b8bc075e54b9,426858038e6a
b8bc075e54b9,46541abeea3a
b8bc075e54b9,ae71ea5f3e42
b8bc075e54b9,61e70da6473a
b8bc075e54b9,ad512a22aa14
b8bc075e54b9,c28869d3de44
b8bc075e54b9,ece00599811b
b8bc075e54b9,0308f810023c
b8bc075e54b9,e0790016c9a5
b8bc075e54b9,7cd7e14bc366
b8bc075e54b9,ca5041eb1ee3
b8bc075e54b9,f31ddc7e876b
b8bc075e54b9,95939880dd3a
b8bc075e54b9,a0cf4907e17e
b8bc075e54b9,06803223b7bf
b8bc075e54b9,46ebdafa5b9e
b8bc075e54b9,9a689f5adfd5
b8bc075e54b9,638f09ddc7b0
b8bc075e54b9,0dfc3565d66c
b8bc075e54b9,8636ab0822ac
b8bc075e54b9,132723a8fe5c
b8bc075e54b9,318d84a2d7db
b8bc075e54b9,71a22d42606b
b8bc075e54b9,30b40ace5eb8
b8bc075e54b9,ced4ab8d6a40
b8bc075e54b9,2e70f4ef6fed
b8bc075e54b9,d6abf6067114
b8bc075e54b9,a7fc3eed5b4d
b8bc075e54b9,4474624368cc
49194b3720b6,057b9bfb4420
49194b3720b6,d627522f3984
49194b3720b6,c391658a19c7
49194b3720b6,dc42eb35fdc2
49194b3720b6,17cdaa697248
49194b3720b6,73bb8bfd3e3d
49194b3720b6,47d9a9418d7a
49194b3720b6,a34eff021e02
49194b3720b6,cc2a82038185
49194b3720b6,7819c621e29e
49194b3720b6,14a76ad97098
49194b3720b6,60c9400712b3
49194b3720b6,0e90502cef04
49194b3720b6,65abc03ca0d4
49194b3720b6,61e70da6473a
49194b3720b6,a7fc3eed5b4d
f0f5962bbc52,c4f33679edb6
f0f5962bbc52,6f74ac703ce5
f0f5962bbc52,dfc5f5d28951
f0f5962bbc52,3a78f54b92b8
f0f5962bbc52,86ea8846e3b8
f0f5962bbc52,1c9a5e4f9641
f0f5962bbc52,0308f810023c
f0f5962bbc52,06803223b7bf
f0f5962bbc52,ced4ab8d6a40
d42f06d92a52,1d54d57a01a7
d42f06d92a52,ba4dd06ef108
d42f06d92a52,307cbfe561e1
d42f06d92a52,68a329c47450
d42f06d92a52,75cb518fc43a
d42f06d92a52,fad9e7cdced2
d42f06d92a52,28e6c0f5e52e
d42f06d92a52,f2ea8d8104df
d42f06d92a52,b04034ef703e
d42f06d92a52,4539897211ee
d42f06d92a52,21f8c9514f94
d42f06d92a52,c595540965cd
d42f06d92a52,93ec94496e8e
d42f06d92a52,60c9400712b3
d42f06d92a52,ea0ab6875037
d42f06d92a52,ad512a22aa14
81123b29ee66,2e1f49d39407
81123b29ee66,846e2499e288
81123b29ee66,6bcf6e2c5e65
81123b29ee66,fa7b3e50f363
81123b29ee66,82d7669e7ef3
81123b29ee66,df45b11bd8d5
81123b29ee66,b0b3a30d69e7
81123b29ee66,24d0660aca2f
81123b29ee66,7cd7e14bc366
b1b65a546a3e,2fa428847959
b1b65a546a3e,28e6c0f5e52e
b1b65a546a3e,a409c26e11ec
b1b65a546a3e,67971a1581b4
b1b65a546a3e,047174fbec38
b1b65a546a3e,5efe3e485d24
b1b65a546a3e,b2612726fe0a
b1b65a546a3e,d4d1284b0171
b1b65a546a3e,496f9568e2f3
b1b65a546a3e,00c9cb6a1baa
b1b65a546a3e,65abc03ca0d4
b1b65a546a3e,823c1b7a7c53
b712b1359e68,15c0812dceff
b712b1359e68,d19a3fd66a47
b712b1359e68,511654bb6c8d
b712b1359e68,046be2240556
b712b1359e68,426858038e6a
c2833a91454a,f8b71643a4c1
c2833a91454a,9a058cf2e094
c2833a91454a,07921bdec548
c2833a91454a,498fb98f60ad
c2833a91454a,2fa428847959
c2833a91454a,51d1ba826cae
c2833a91454a,93ded5f4a9a2
c2833a91454a,d675d6e7b7a6
c2833a91454a,caa08f80c71b
c2833a91454a,496f9568e2f3
c2833a91454a,a8874b9e61b9
c2833a91454a,ed4c1ddc5aae
c2833a91454a,d93100708b01
c2833a91454a,1489f5578712
c2833a91454a,65abc03ca0d4
c2833a91454a,61e70da6473a
c2833a91454a,132723a8fe5c
c2833a91454a,318d84a2d7db
c2833a91454a,4474624368cc
993a9b1dc2ef,0067b245d95d
993a9b1dc2ef,6dbf201074fb
993a9b1dc2ef,7781f0de6ec5
993a9b1dc2ef,891b42ed781b
993a9b1dc2ef,29433f28f16a
993a9b1dc2ef,38c13d1ef64f
993a9b1dc2ef,08c8ca492c96
1d54d57a01a7,cbba789fcc68
1d54d57a01a7,ba4dd06ef108
1d54d57a01a7,307cbfe561e1
1d54d57a01a7,2631addff82d
1d54d57a01a7,1e6e14ca2e81
1d54d57a01a7,05e4c05872de
1d54d57a01a7,68a329c47450
1d54d57a01a7,69783db11b2c
1d54d57a01a7,75cb518fc43a
1d54d57a01a7,83c1cc7798a8
1d54d57a01a7,40f7e1e55de6
1d54d57a01a7,fad9e7cdced2
1d54d57a01a7,83b10ce23373
1d54d57a01a7,55fcf51c7aa0
1d54d57a01a7,47d9a9418d7a
1d54d57a01a7,28e6c0f5e52e
1d54d57a01a7,fe38f482a16e
1d54d57a01a7,cc2a82038185
1d54d57a01a7,f7725a623ac8
1d54d57a01a7,0fcd9bb9fc31
1d54d57a01a7,f2ea8d8104df
1d54d57a01a7,9b7a5086a83b
1d54d57a01a7,a409c26e11ec
1d54d57a01a7,76d3592668ee
1d54d57a01a7,047174fbec38
1d54d57a01a7,b04034ef703e
1d54d57a01a7,2715a83c4a9d
1d54d57a01a7,343f5345b6b9
1d54d57a01a7,2170d3b4ad9e
1d54d57a01a7,4539897211ee
1d54d57a01a7,74d3e94c38d3
1d54d57a01a7,21f8c9514f94
1d54d57a01a7,794bc256e2a8
1d54d57a01a7,5cf03340ca7a
1d54d57a01a7,c674da4a8e15
1d54d57a01a7,c25036408eef
1d54d57a01a7,a6251a50e6c5
1d54d57a01a7,e3a14c0757e2
1d54d57a01a7,88f358a6080a
1d54d57a01a7,5446c664fe14
1d54d57a01a7,995122436f7b
1d54d57a01a7,20f5c0dc2f23
1d54d57a01a7,60c9400712b3
1d54d57a01a7,a2c31422625c
1d54d57a01a7,ed4c1ddc5aae
1d54d57a01a7,2c4cac92459a
1d54d57a01a7,924f73dea209
1d54d57a01a7,d93100708b01
1d54d57a01a7,65abc03ca0d4
1d54d57a01a7,61e70da6473a
1d54d57a01a7,ad512a22aa14
1d54d57a01a7,ca5041eb1ee3
1d54d57a01a7,46ebdafa5b9e
1d54d57a01a7,71a22d42606b
1d54d57a01a7,30b40ace5eb8
79ff489ecbc1,68a329c47450
79ff489ecbc1,f2ea8d8104df
79ff489ecbc1,047174fbec38
79ff489ecbc1,21f8c9514f94
79ff489ecbc1,20f5c0dc2f23
79ff489ecbc1,a2c31422625c
79ff489ecbc1,ed4c1ddc5aae
79ff489ecbc1,ad512a22aa14
79ff489ecbc1,a0cf4907e17e
bd51b54aa99c,cbba789fcc68
bd51b54aa99c,307cbfe561e1
bd51b54aa99c,1e6e14ca2e81
bd51b54aa99c,d2813865c79c
bd51b54aa99c,498fb98f60ad
bd51b54aa99c,68a329c47450
bd51b54aa99c,ff7499af5148
bd51b54aa99c,b3a4c8f2a36b
bd51b54aa99c,55818c401f3a
bd51b54aa99c,c37579407447
bd51b54aa99c,47d9a9418d7a
bd51b54aa99c,9b7a5086a83b
bd51b54aa99c,c920d8c7a90a
bd51b54aa99c,4539897211ee
bd51b54aa99c,74d3e94c38d3
bd51b54aa99c,ef005800712a
bd51b54aa99c,c45efbd21270
bd51b54aa99c,14a76ad97098
bd51b54aa99c,b48207900b75
bd51b54aa99c,6fc4693e7953
bd51b54aa99c,a6251a50e6c5
bd51b54aa99c,b44b67bfcbd8
bd51b54aa99c,8f72f6bc69e5
bd51b54aa99c,88f358a6080a
bd51b54aa99c,20f5c0dc2f23
bd51b54aa99c,d93100708b01
bd51b54aa99c,45ee2528da2b
bd51b54aa99c,ece00599811b
bd51b54aa99c,a0cf4907e17e
bd51b54aa99c,30b40ace5eb8
4ebf721a9462,c4f33679edb6
4ebf721a9462,8de38b5be85e
4ebf721a9462,1e498fd35e79
4ebf721a9462,6f74ac703ce5
4ebf721a9462,dfc5f5d28951
4ebf721a9462,a8e84e79fd16
4ebf721a9462,3a78f54b92b8
4ebf721a9462,b2794e41d0cc
4ebf721a9462,66424a2f0ee2
4ebf721a9462,86ea8846e3b8
4ebf721a9462,51f45ed19f95
4ebf721a9462,1c9a5e4f9641
4ebf721a9462,0308f810023c
4ebf721a9462,ced4ab8d6a40
b4bbd056ae56,985e342b613a
b4bbd056ae56,ff7499af5148
b4bbd056ae56,c37579407447
b4bbd056ae56,c920d8c7a90a
b4bbd056ae56,b44b67bfcbd8
b4bbd056ae56,ca5041eb1ee3
b4bbd056ae56,95939880dd3a
b4bbd056ae56,a0cf4907e17e
83c0e39eb091,2e935226520b
83c0e39eb091,1e498fd35e79
83c0e39eb091,8700ea0ec29d
83c0e39eb091,6f74ac703ce5
83c0e39eb091,dfc5f5d28951
83c0e39eb091,b2e9130ceb77
83c0e39eb091,b27c1f55f390
83c0e39eb091,a8e84e79fd16
83c0e39eb091,66424a2f0ee2
83c0e39eb091,51f45ed19f95
83c0e39eb091,1c9a5e4f9641
83c0e39eb091,0308f810023c
2e935226520b,1e498fd35e79
2e935226520b,15c0812dceff
2e935226520b,3617f6cbcded
2e935226520b,6f74ac703ce5
2e935226520b,63ab94d24452
2e935226520b,be930e7580f2
2e935226520b,d14046199f56
2e935226520b,66424a2f0ee2
2e935226520b,e9beb574a089
2e935226520b,a5d1dfaf0bba
2e935226520b,58a9e2f8cdc3
2e935226520b,1c9a5e4f9641
2e935226520b,426858038e6a
2e935226520b,ced4ab8d6a40
c4f33679edb6,1e498fd35e79
c4f33679edb6,08452885ff12
c4f33679edb6,8700ea0ec29d
c4f33679edb6,6f74ac703ce5
c4f33679edb6,3a78f54b92b8
c4f33679edb6,375338afd04b
c4f33679edb6,66424a2f0ee2
c4f33679edb6,86ea8846e3b8
c4f33679edb6,1c9a5e4f9641
c4f33679edb6,0308f810023c
c4f33679edb6,06803223b7bf
c4f33679edb6,ced4ab8d6a40
cbba789fcc68,ba4dd06ef108
cbba789fcc68,307cbfe561e1
cbba789fcc68,9a058cf2e094
cbba789fcc68,75f2e606f05c
cbba789fcc68,45a669e4fc6a
cbba789fcc68,333de2dc16dc
cbba789fcc68,1e6e14ca2e81
cbba789fcc68,05e4c05872de
cbba789fcc68,68a329c47450
cbba789fcc68,17cdaa697248
cbba789fcc68,b3a4c8f2a36b
cbba789fcc68,742b6e5b64d7
cbba789fcc68,83b10ce23373
cbba789fcc68,cd4efa39228a
cbba789fcc68,55818c401f3a
cbba789fcc68,47d9a9418d7a
cbba789fcc68,68d8e44b5776
cbba789fcc68,28e6c0f5e52e
cbba789fcc68,80b059535dc9
cbba789fcc68,676e3d882946
cbba789fcc68,f7725a623ac8
cbba789fcc68,d675d6e7b7a6
cbba789fcc68,f2ea8d8104df
cbba789fcc68,bcf9895c77e8
cbba789fcc68,76d3592668ee
cbba789fcc68,6a5e3c080139
cbba789fcc68,047174fbec38
cbba789fcc68,b04034ef703e
cbba789fcc68,affc5cad4bbf
cbba789fcc68,2170d3b4ad9e
cbba789fcc68,4539897211ee
cbba789fcc68,2e45ab95414f
cbba789fcc68,21f8c9514f94
cbba789fcc68,794bc256e2a8
cbba789fcc68,ada5696ad597
cbba789fcc68,c45efbd21270
cbba789fcc68,c25036408eef
cbba789fcc68,00c9cb6a1baa
cbba789fcc68,14a76ad97098
cbba789fcc68,6fc4693e7953
cbba789fcc68,ac6f84e69823
cbba789fcc68,3d79e076cf01
cbba789fcc68,a6251a50e6c5
cbba789fcc68,88f358a6080a
cbba789fcc68,5446c664fe14
cbba789fcc68,93ec94496e8e
cbba789fcc68,20f5c0dc2f23
cbba789fcc68,60c9400712b3
cbba789fcc68,233a7ee80e3b
cbba789fcc68,bc91db5c349c
cbba789fcc68,924f73dea209
cbba789fcc68,d93100708b01
cbba789fcc68,1489f5578712
cbba789fcc68,45ee2528da2b
cbba789fcc68,65abc03ca0d4
cbba789fcc68,61e70da6473a
cbba789fcc68,ad512a22aa14
cbba789fcc68,ece00599811b
cbba789fcc68,a0cf4907e17e
cbba789fcc68,46ebdafa5b9e
cbba789fcc68,30b40ace5eb8
cbba789fcc68,d6abf6067114
f8b71643a4c1,2fa428847959
f8b71643a4c1,67971a1581b4
f8b71643a4c1,caa08f80c71b
f8b71643a4c1,343f5345b6b9
f8b71643a4c1,20f5c0dc2f23
f8b71643a4c1,1489f5578712
f8b71643a4c1,c28869d3de44
f8b71643a4c1,132723a8fe5c
f8b71643a4c1,4474624368cc
44946ad84360,eb0037580902
44946ad84360,440af1812334
44946ad84360,0776cf5a0850
44946ad84360,d3d5d226a79b
44946ad84360,dfc5f5d28951
44946ad84360,af1ea5d543a6
44946ad84360,a8e84e79fd16
44946ad84360,0491a87eca39
44946ad84360,d14046199f56
44946ad84360,3afb02ef6420
44946ad84360,e9beb574a089
44946ad84360,c94af46d6fe7
44946ad84360,954f9dc02c38
44946ad84360,2040929b91d8
44946ad84360,29433f28f16a
44946ad84360,0289cf827470
c256266e0958,d627522f3984
c256266e0958,740522c85adc
c256266e0958,52102636a852
c256266e0958,73bb8bfd3e3d
c256266e0958,7e49bcf5ebb3
c256266e0958,f5e2392562b2
c256266e0958,5efe3e485d24
c256266e0958,b2612726fe0a
c256266e0958,7819c621e29e
c256266e0958,715f6cc1b260
c256266e0958,cae91f31aa84
c256266e0958,e5160cec7608
c256266e0958,0e90502cef04
c256266e0958,f78244826bcd
c256266e0958,a7fc3eed5b4d
ba4dd06ef108,307cbfe561e1
ba4dd06ef108,9a058cf2e094
ba4dd06ef108,75f2e606f05c
ba4dd06ef108,45a669e4fc6a
ba4dd06ef108,eb0037580902
ba4dd06ef108,1e6e14ca2e81
ba4dd06ef108,498fb98f60ad
ba4dd06ef108,68a329c47450
ba4dd06ef108,69783db11b2c
ba4dd06ef108,75cb518fc43a
ba4dd06ef108,dc42eb35fdc2
ba4dd06ef108,5613f7f5b5cc
ba4dd06ef108,40f7e1e55de6
ba4dd06ef108,0776cf5a0850
ba4dd06ef108,3c39f7406253
ba4dd06ef108,17cdaa697248
ba4dd06ef108,7e49bcf5ebb3
ba4dd06ef108,b3a4c8f2a36b
ba4dd06ef108,51d1ba826cae
ba4dd06ef108,742b6e5b64d7
ba4dd06ef108,83b10ce23373
ba4dd06ef108,55fcf51c7aa0
ba4dd06ef108,47d9a9418d7a
ba4dd06ef108,28e6c0f5e52e
ba4dd06ef108,c8823edd6529
ba4dd06ef108,0fcd9bb9fc31
ba4dd06ef108,9b7a5086a83b
ba4dd06ef108,67971a1581b4
ba4dd06ef108,047174fbec38
ba4dd06ef108,b04034ef703e
ba4dd06ef108,2715a83c4a9d
ba4dd06ef108,343f5345b6b9
ba4dd06ef108,2170d3b4ad9e
ba4dd06ef108,4539897211ee
ba4dd06ef108,74d3e94c38d3
ba4dd06ef108,21f8c9514f94
ba4dd06ef108,794bc256e2a8
ba4dd06ef108,f44ff56c2769
ba4dd06ef108,5cf03340ca7a
ba4dd06ef108,c674da4a8e15
ba4dd06ef108,c25036408eef
ba4dd06ef108,14a76ad97098
ba4dd06ef108,954f9dc02c38
ba4dd06ef108,6fc4693e7953
ba4dd06ef108,a8874b9e61b9
ba4dd06ef108,a6251a50e6c5
ba4dd06ef108,132aa73e02b2
ba4dd06ef108,c35cb09ad753
ba4dd06ef108,88f358a6080a
ba4dd06ef108,5446c664fe14
ba4dd06ef108,995122436f7b
ba4dd06ef108,20f5c0dc2f23
ba4dd06ef108,60c9400712b3
ba4dd06ef108,ea0ab6875037
ba4dd06ef108,a2c31422625c
ba4dd06ef108,41d0f5691fa4
ba4dd06ef108,d37b23aa26a9
ba4dd06ef108,ed4c1ddc5aae
ba4dd06ef108,924f73dea209
ba4dd06ef108,61e70da6473a
ba4dd06ef108,ad512a22aa14
ba4dd06ef108,ece00599811b
ba4dd06ef108,95939880dd3a
ba4dd06ef108,a0cf4907e17e
ba4dd06ef108,638f09ddc7b0
307cbfe561e1,45a669e4fc6a
307cbfe561e1,333de2dc16dc
307cbfe561e1,1e6e14ca2e81
307cbfe561e1,31cb4a596cdc
307cbfe561e1,05e4c05872de
307cbfe561e1,68a329c47450
307cbfe561e1,69783db11b2c